// VOTE CONSTANT
export const ADD_ONE_TO_VOTE = "ADD_ONE_TO_VOTE";
export const MINUS_ONE_TO_VOTE = "MINUS_ONE_TO_VOTE";

// COMMENT CONSTANT
export const ADD_COMMENT = "ADD_COMMENT";

// ADD POST CONSTANT
export const ADD_POST = "ADD_POST";

// USERS CONSTANTS
export const USER_LOGGING_IN = "USER_LOGGING_IN";
export const USER_LOGGED_IN = "USER_LOGGED_IN";